### ISSUE TITLE
General Code Review (Ashley)

### ISSUE THREAD

**Issue by AshleyLerma** [juanlajara/Portfolio-Season-2#2]
I will review your code and leave input here

**Comment by AshleyLerma** [comment]
Ashley's code review: 

**Praise:**

- Your ReadMe is very thorough. I know this is one of your strong suits from our projects but it is nice to see the consistency when it comes to your portfolio as well. 
- The portfolio as a whole is very responsive and professional looking.  
- Your code is well organized and the folders are easy to navigate through. 
- You have a very effective use of props throughout your components. This will make it much easier to update any information as time goes on. The use of props to this extend shows a great grasp of React and takes full advantage of reusable components. Very impressive!

**Questions:** 

- Is there a reason you chose to deploy on Heroku instead of GitHub? 
- Is there a reason you used class based components as opposed to functional react components? 

**Recommendations:**

- I would suggest you add a target="blank" for your live link in the ReadMe and all links within your portfolio site. This would make the site more user friendly. 
- At certain screen sizes your portfolio section doesn't re-arrange correctly and will leave one project miss-aligned. If you change the size or adjust with an added jquery you may be able to solve this.  
- Your facebook and linked in both route to a sign in page instead of your profile. I would either remove or update these. 
- There are 11 errors and 2 warning when you inspect the live link. I didn't have time to go through these one by one but I would take some time to discover why that is happening. 
- Your commits give a vague idea of what you were working on but often seem to tackle to large of items. It would be easier to follow the process and each individual step (and easier to troubleshoot) if you committed with greater frequency. 
- I don't see any comments or Todos written in your code so it it sometimes time consuming to analyze the purpose of a code block or to determine what your plans on for further improvement.

**Comment by juanlajara** [comment]
Cleaned up all of the above and applied suggestions
